# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: sablier-lockup
unordered_multichain_mode: true
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"
    - "value"
contracts:
  - name: LockupV20
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CancelLockupStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint128
          senderAmount, uint128 recipientAmount)
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint40,uint40,uint40) range,
          address broker)
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, (uint128,uint64,uint40)[] segments,
          (uint40,uint40) range, address broker)
      - event: RenounceLockupStream(uint256 indexed streamId)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event: WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, uint128 amount)
  - name: LockupV21
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CancelLockupStream(uint256 streamId, address indexed sender, address indexed recipient, address indexed asset,
          uint128 senderAmount, uint128 recipientAmount)
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint40,uint40,uint40) range, address broker)
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint64,uint40)[] segments, (uint40,uint40) range, address broker)
      - event: RenounceLockupStream(uint256 indexed streamId)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event:
          WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, address indexed asset, uint128 amount)
  - name: LockupV22
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CancelLockupStream(uint256 streamId, address indexed sender, address indexed recipient, address indexed asset,
          uint128 senderAmount, uint128 recipientAmount)
      - event:
          CreateLockupLinearStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint40,uint40,uint40) timestamps, address broker)
      - event:
          CreateLockupDynamicStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint64,uint40)[] segments, (uint40,uint40) timestamps, address broker)
      - event:
          CreateLockupTranchedStream(uint256 streamId, address funder, address indexed sender, address indexed recipient,
          (uint128,uint128) amounts, address indexed asset, bool cancelable, bool transferable,
          (uint128,uint40)[] tranches, (uint40,uint40) timestamps, address broker)
      - event: RenounceLockupStream(uint256 indexed streamId)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event:
          WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, address indexed asset, uint128 amount)
  - name: LockupV23
    handler: src/mappings/index.ts
    events:
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CancelLockupStream(uint256 streamId, address indexed sender, address indexed recipient, address indexed token,
          uint128 senderAmount, uint128 recipientAmount)
      - event:
          CreateLockupLinearStream(uint256 indexed streamId,(address,address,address,(uint128,uint128),address,bool,bool,(uint40,uint40),string,address) commonParams,
          uint40 cliffTime,(uint128,uint128) unlockAmounts)
      - event:
          CreateLockupDynamicStream(uint256 indexed streamId,(address,address,address,(uint128,uint128),address,bool,bool,(uint40,uint40),string,address) commonParams,
          (uint128,uint64,uint40)[] segments)
      - event:
          CreateLockupTranchedStream(uint256 indexed streamId,(address,address,address,(uint128,uint128),address,bool,bool,(uint40,uint40),string,address) commonParams,
          (uint128,uint40)[] tranches)
      - event: RenounceLockupStream(uint256 indexed streamId)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event:
          WithdrawFromLockupStream(uint256 indexed streamId, address indexed to, address indexed token, uint128 amount)
networks:
  - id: 11155111
    start_block: 4067889
    contracts:
      - name: LockupV20
        address:
          - 0xd4300c5bc0b9e27c73ebabdc747ba990b1b570db
          - 0x421e1e7a53ff360f70a2d02037ee394fa474e035
      - name: LockupV21
        address:
          - 0x7a43f8a888fa15e68c103e18b0439eb1e98e4301
          - 0xc9940ad8f43aad8e8f33a4d5dbbf0a8f7ff4429a
      - name: LockupV22
        address:
          - 0x3e435560fd0a03ddf70694b35b673c25c65abb6c
          - 0x73bb6dd3f5828d60f8b3dbc8798eb10fba2c5636
          - 0x3a1bea13a8c24c0ea2b8fae91e4b2762a59d7af5
      - name: LockupV23
        address:
          - 0x2dbce44ad5f944e5a588c516c408462c28b1f786
